<?php

/* @var $this Mage_Core_Block_Template */
/* @var $catalogSearchHelper Mage_Catalogsearch_Helper_Data */
$catalogSearchHelper =  $this->helper('catalogsearch');
?>

<?php 
    $category = Mage::getModel('catalog/category'); 
    if(is_object(Mage::registry('current_category'))){ 
        $currentCategoryPath=Mage::registry('current_category')->getPathIds(); 
    }else{ 
        $currentCategoryPath = array(); 
    } 
    $category->load(Mage::app()->getStore()->getRootCategoryId()); 
    $childrenString = $category->getChildren(); 
    $children = explode(',',$childrenString); 
    $categoryOptions=''; 
    foreach($children as $c){ 
        if($this->getRequest()->getParam('cat')==""){ 
            $selected = (in_array($c, $currentCategoryPath))?'SELECTED':''; 
        }else{ 
            $selected = ($this->getRequest()->getParam('cat')==$c)?'SELECTED':''; 
    } 
    $categoryOptions.= '<option value="' . $c . '" ' . $selected . '>' . $category->load($c)->getName() . '</option>' . "\n"; 
    } 
?>

<div class="search-box">
 <form id="search_mini_form" action="<?php echo $this->helper('catalogsearch')->getResultUrl() ?>" method="get"> 
        <input id="search" type="text" name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>" value="<?php echo $this->helper('catalogsearch')->getEscapedQueryText() ?>" class="searchbox" /> 
        <select name="cat" id="cat" class="search-cat"> 
            <option value=""><?php echo $this->__('All') ?></option> 
            <?php echo $categoryOptions ?> 
        </select> 
        <button type="submit" title="<?php echo $this->__('Search') ?>" class="button-common search-btn-bg"><span class="searchIconNew"></span></button> 
        <div id="search_autocomplete" class="search-autocomplete"></div> 
        <script type="text/javascript"> 
        //<![CDATA[ 
            var searchForm = new Varien.searchForm('search_mini_form', 'search', '<?php echo $this->__('Search') ?>'); 
            searchForm.initAutocomplete('<?php echo $this->helper('catalogsearch')->getSuggestUrl() ?>', 'search_autocomplete'); 
        //]]> 
        </script>
</form>
</div> <!--search-box-->
