<?php
/**
 * Template file for PayU - Credit Card payment method additional form.
 *
 * @category    Innobyte
 * @package     Innobyte_PayULite
 * @author      Bogdan Constantinescu <bogdan.constantinescu@innobyte.com>
 */

// @var $this   Innobyte_PayULite_Block_Form_Cc
?>

<?php $_code = $this->getMethodCode(); ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <div class="f-left">
            <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
            <div class="input-box f-left">
                <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry">
                    <option value=""><?php echo $this->__('--Please Select--')?></option>
                <?php $_ccType = $this->getInfoData('cc_type') ?>
                <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                    <option value="<?php echo $_typeCode ?>"<?php if ($_typeCode == $_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </div>
        <img src="<?php echo $this->getSkinUrl('images/innobyte/payu-lite/secure-1-2.png'); ?>" alt="" width="200" height="60" class="f-right" />
        <br style="clear: both;" />
    </li>
</ul>
