
<?php
/**
 * Cart cross sell items template
 *
 * @see Mage_Checkout_Block_Cart_Crosssell
 */
?>
<?php if($this->getItemCount()): ?>
<div class="crosssel">
 <div class="category-products">
  <div class="best-sales-slider">
    <h2><?php echo $this->__('you may be interested in the following items:') ?></h2>
    <ul id="crosssell-products-list" class="products-grid">
    <?php foreach ($this->getItems() as $_item): ?>
        <li class="item">
                 <div class="item-inner">
                   <div class="item-img">
                     <div class="item-img-info">
                       <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_item, 'small_image'), null, true) ?>" class="product-image">
                          <img src="<?php echo $this->helper('catalog/image')->init($_item, 'small_image')->resize(245,245); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_item, 'small_image'), null, true) ?>" />                    
                       </a>
                       <?php echo $this->helper('innovasettings')->getLabel($_item);  ?>                    
                     </div> <!--item-img-info-->
                   </div> <!--item-img-->

                  <div class="item-info">
                    <div class="info-inner">
                       <div class="item-title">
                        <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>">
                           <?php $prod_name = $this->htmlEscape($_item->getName()) ; 
                           if(strlen($prod_name) > 20) {echo substr($prod_name,0,20)."...";}else {echo $prod_name;}?>
                        </a>
                       </div> <!--item-title-->
                       <div class="item-content">
                          <?php echo $this->getReviewsSummaryHtml($_item, 'short') ?>
                          <div class="item-price">
                             <?php echo $this->getPriceHtml($_item, true) ?>
                          </div> <!--item-price-->
                       </div> <!--item-content-->
                    </div> <!--info-inner-->

                     <div class="actions">
                       <span class="add-to-links">
                          <?php if ($this->helper('wishlist')->isAllow()) : ?>
                             <a href="<?php echo $this->helper('wishlist')->getAddUrl($_item) ?>" class="link-wishlist" title="<?php echo $this->__('Add to wishlist');?>"></a>
                          <?php endif; ?>
                          <?php if($_item->isSaleable()): ?>
                             <button type="button"  title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_item) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
                          <?php else: ?>
                             <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                          <?php endif; ?>
                          <?php if($_compareUrl=$this->getAddToCompareUrl($_item)): ?>
                             <a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to compare');?>"></a>
                          <?php endif; ?> 
                       </span> <!--add-to-links-->
                     </div> <!--actions-->

                  </div> <!--item-info-->
                 </div> <!--item-inner-->       
        </li>
    <?php endforeach; ?>
    </ul>
    <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script>
  </div> <!--best-sales-slider-->
 </div> <!--category-products-->
</div>  <!--crosssel-->
<?php endif; ?>
