
<?php
                // some helpers
                $_helper = $this->helper('catalog/output');
                $storeId = Mage::app()->getStore()->getId();
                $catalog = $this->getLayout()->createBlock('catalog/product_list')->setStoreId($storeId);
                $productCount = $this->getData('num_products');
$visibility = array(
                      Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH,

                      Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
 
                  );
$collection = Mage::getResourceModel('reports/product_collection')
                        ->addAttributeToSelect('*')    
                        ->setStoreId($storeId)
                        ->addStoreFilter($storeId)    
                        ->addAttributeToFilter('visibility', $visibility)
                        ->setPageSize($productCount);
$collection->getSelect()->order('rand()');
Mage::getSingleton('catalog/product_status')->addVisibleFilterToCollection($collection);
Mage::getSingleton('catalog/product_visibility')->addVisibleInCatalogFilterToCollection($collection);
$collection->joinField('is_in_stock','cataloginventory/stock_item','is_in_stock','product_id=entity_id')->addAttributeToFilter('is_in_stock', 1);

/* To display product by category id */
 if($categoryId=$this->getData('category_id')){
        $category = Mage::getModel('catalog/category')->load($categoryId);
        $collection->addCategoryFilter($category);
      }
                // if no products , display some text
                 if (!$collection->count()) :
        ?>
        <p class="note-msg"><?php echo $this->__('There are no products at the moment.') ?></p>
        <?php else : ?>

<div class="row">
  <div class="custom-box">
     <div class="custom-block"><?php echo $this->__('RANDOM PRODUCTS') ?> <a href="#"><?php echo $this->__('SEE MORE') ?></a></div>
  </div> <!--custom-box-->
</div> <!--row-->


<div class="row">
        <?php
                $_collectionSize = $collection->count();
                $_columnCount = 4;
                $i = 0;                
                foreach ($collection as $_product) :
                        $_product = Mage::getModel('catalog/product')->setStoreId($storeId)->load($_product->getId());

        ?>
        <?php if ($i++%$_columnCount==0): ?>            
        <?php endif ?>
<div class="grid5 <?php if(($i-1)%$_columnCount==0): ?>first<?php elseif($i%$_columnCount==0): ?> last<?php elseif($i%$_columnCount!==0): ?> odd<?php endif; ?>">
  <div class="row">
    <div class="grid12">
      <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300,300) ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
    </div> <!--grid12-->
    <div class="grid12">
      <div class="pr-title">
         <?php $prod_name = $this->htmlEscape($_product->getName()) ; 
                  if(strlen($prod_name) > 20) {echo substr($prod_name,0,20)."...";} else {echo $prod_name;} ?> 
      </div> <!--pr-title-->
      <div class="pr-price">
         <?php echo $this->getPriceHtml($_product, true) ?>
      </div> <!--pr-price-->
      <div>
          <?php if($_product->isSaleable()): ?>
              <button type="button" title="<?php echo $this->__('BUY NOW') ?>" class="button-buy" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('BUY NOW') ?></span></button>                                         
          <?php else: ?>
              <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
          <?php endif; ?>
      </div> 
    </div> <!--grid12-->
  </div> <!--row-->
</div> <!--grid5 last-->      
            <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>            
            <?php endif ?>            
                <?php endforeach ?>
 
</div> <!--row-->

        <?php endif ?>  <!-- endif (!$collection->count()) -->
