<br />
<p>Tranzactia a fost refuzata din unul dintre urmatoarele motive:</p>
<ul style="text-indent:10px">
<li>- datele cardului au fost introduse incorect;</li>
<li>- nu exista fonduri suficiente in contul cardului;</li>
<li>- banca emitenta a refuzat tranzactia datorita unor restrictii de securitate impuse cardului sau tipul de card folosit nu este acceptat;</li>
<li>- reteaua de tranzactionare este momentan indisponibila.</li>
</ul>
<p>Va recomandam sa reluati procesarea tranzactiei in cateva minute, dupa efectuarea schimbarilor necesare</p>