<?php if($this->getCurrencyCount() > 1): ?>
<!-- BEGIN BLOCK CURRENCY -->
<div class="currency-box">
  <div class="currency-switcher">       
    <div class="currency_detail" style="display: none;">
      <div class="currency-inner">
         <?php foreach ($this->getCurrencies() as $_code => $_name):?>               
              <a href="<?php echo $this->getSwitchCurrencyUrl($_code) . '?___store='.$_code;?>" title="<?php echo $this->htmlEscape($_code) ?>" <?php if($_code==$this->getCurrentCurrencyCode()){?>
          class="currency_icon selected "<?php } else {?> class="currency_icon"<?php }?>> <span><?php echo Mage::app()->getLocale()->currency($_code)->getSymbol(); ?> - <?php echo $_code; ?></span> 
              </a>               
         <?php endforeach; ?>
      </div> <!--currency-inner-->
    </div> <!--currency_detail-->
    <div class="select_curr">
     <span> <?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?> </span> <span class="caret"></span>
    </div> <!--select_curr-->
  </div> <!--currency-switcher--> 

<script type="text/javascript">
        jQuery(function() {
                jQuery(".currency-switcher").hover(function() {
                        jQuery('.select_curr').addClass('active');
                        jQuery(".currency_detail").stop(true, true).slideDown(200, "easeInSine");
                        },  
                        function() {
                        jQuery('.select_curr').removeClass('active');
                        jQuery(".currency_detail").stop(true, true).fadeOut(100, "easeInCubic");
                        });

        });
</script>
 
</div> <!--currency-box-->
<?php endif; ?> 
