<?php 
	if (Mage::getStoreConfig('mm_extra/am_vazut_si_nea_placut/produs')!=''){
	$_product = Mage::getModel('catalog/product')->loadByAttribute('sku',Mage::getStoreConfig('mm_extra/am_vazut_si_nea_placut/produs'));
	//var_dump($product);
?>
	<div class="item-inner">
                <div class="item-img">
                  <div class="item-img-info">
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                      <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(245,245); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />                
                    </a>
                     <?php echo $this->helper('innovasettings')->getLabel($_product);  ?>
                   <?php if(Mage::app()->getStore()->getConfig('innovasettings/innovasettings_quickview/enable')==1){?>
                    <div class="item-box-hover">
                       <div class="box-inner">
                          <div class="product-detail-bnt">
                              <a data-fancybox-type="ajax" onclick="callQuickView('<?php echo Mage::getUrl('innovasettings/index/view/id/'.$_product->getId());?>');" title="<?php echo $this->__('Quick View') ?>" class="button detail-bnt"><span><?php echo $this->__('Quick View') ?></span></a>                    
                          </div> <!--product-detail-bnt-->
                       </div> <!--box-inner-->
                    </div> <!--item-box-hover-->
                   <?php } ?>
                  </div> <!--item-img-info-->
                </div> <!--item-img-->
                <div class="item-info">
                  <div class="info-inner">
                    <div class="item-title">
                        <a class="product-name" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                          <?php $prod_name = $this->htmlEscape($_product->getName()) ; 
                           if(strlen($prod_name) > 20) {echo substr($prod_name,0,20)."...";}else {echo $prod_name;}?>
                        </a>
                    </div> <!--item-title-->
                    <div class="item-content">
                       <?php  if($_product->getRatingSummary()): ?>
                         <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                       <?php else: ?>
                          <div class="no-rating-box-blank"><div class="no-rating-box"></div></div>
                       <?php  endif;  ?>
                       <div class="item-price">
                          <?php echo $this->getPriceHtml($_product, true) ?>
                       </div> <!--item-price-->
                    </div> <!--item-content-->
                  </div> <!--info-inner-->
                  <div class="actions">
                     <span class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                          <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" title="<?php echo $this->__('Add to wishlist');?>"></a>
                        <?php endif; ?>
                        <?php if($_product->isSaleable()): ?>
                          <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
                        <?php else: ?>
                          <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                          <a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to compare');?>"></a>
                        <?php endif; ?>
                     </span> <!--add-to-links-->
                  </div> <!--actions-->
                </div> <!--item-info-->
              </div> <!--item-inner-->
<?php }?>
