<?php
              // some helpers
              $_helper = $this->helper('catalog/output');
              $storeId = Mage::app()->getStore()->getId();
              $catalog = $this->getLayout()->createBlock('catalog/product_list')->setStoreId($storeId);
              $productCount = $this->getData('num_products');

$visibility = array( 
                    Mage_Catalog_Model_Product_Visibility::VISIBILITY_BOTH, 
                    Mage_Catalog_Model_Product_Visibility::VISIBILITY_IN_CATALOG
                );
$attributeInfo = Mage::getResourceModel('eav/entity_attribute_collection')
              ->setCodeFilter('magikfeatured')
              ->getFirstItem();
  $attribute_info = $attributeInfo->getData();
 
  if($attribute_info['attribute_code'] == 'magikfeatured'){
$collection = Mage::getModel('catalog/product')->getCollection() 
                      ->addAttributeToSelect('*')     
                      ->setStoreId($storeId) 
                      ->addStoreFilter($storeId)     
                      ->addAttributeToFilter('visibility', $visibility)
                      ->addAttributeToSelect('magikfeatured')
                      ->addFieldToFilter(array(
						    array('attribute'=>'magikfeatured','eq'=>'1')      
						))
                      ->setOrder('updated_at', 'desc')
                      ->addAttributeToSelect('status') 
                      ->setPageSize(5);
                       Mage::getSingleton('catalog/product_status')->addVisibleFilterToCollection($collection);
                       Mage::getSingleton('catalog/product_visibility')->addVisibleInCatalogFilterToCollection($collection);
$collection->joinField('is_in_stock','cataloginventory/stock_item','is_in_stock','product_id=entity_id')->addAttributeToFilter('is_in_stock', 1);

/*  To display product by category id */
if($categoryId=$this->getData('category_id')){
      $category = Mage::getModel('catalog/category')->load($categoryId);
      $collection->addCategoryFilter($category);
    } ?>

<div class="main-col">


<?php
// if no products are currently featured, display some text
   if (!$collection->count()) :
?>
    <p class="note-msg"><?php echo $this->__('Momentan nu există recomandări de produse.') ?></p>
      
<?php else : ?>

<div class="best-sales-slider std">
<div class="new_title center">
  <h2><span><?php echo $this->__('Recomandări') ?></span></h2>
</div> <!--new_title center-->
<a id="products_slider_prev2" class="jcarousel-prev-horizontal1" href="#"></a>
<a id="products_slider_next2" class="jcarousel-next-horizontal1" href="#"></a>

  <div class="jcarousel-skin-tango5">
    <div class="jcarousel-container jcarousel-container-horizontal" style="position: relative; display: block;">
      <div class="jcarousel-clip jcarousel-clip-horizontal" style="overflow: hidden; position: relative;">
        <ul class="products-grid jcarousel-list jcarousel-list-horizontal" id="products_slider2" style="overflow: hidden; position: relative; top: 0px; margin: 0px; padding: 0px; left: 0px; width: 2452px;">
        <?php
                $_collectionSize = $collection->count();
                $_columnCount = 4;
                $i = 0;
                
                foreach ($collection as $_product) :
                        $_product = Mage::getModel('catalog/product')->setStoreId($storeId)->load($_product->getId());
        ?>
            <?php if ($i++%$_columnCount==0): ?>
            
            <?php endif ?>

                <li class="item jcarousel-item jcarousel-item-horizontal jcarousel-item-1 jcarousel-item-1-horizontal<?php if(($i-1)%$_columnCount==0): ?> first1<?php elseif($i%$_columnCount==0): ?> last1<?php endif; ?>" style="float: left; list-style: none outside none;"> 
                  <div class="item-inner">
                   <div class="item-img">
                     <div class="item-img-info">
                       <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                          <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(245,245); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />                    
                       </a>
                       <?php echo $this->helper('innovasettings')->getLabel($_product);  ?>
                    <?php if(Mage::app()->getStore()->getConfig('innovasettings/innovasettings_quickview/enable')==1){?>
                       <div class="item-box-hover">
                          <div class="box-inner">
                             <div class="product-detail-bnt">
                               <a data-fancybox-type="ajax" onclick="callQuickView('<?php echo Mage::getUrl('innovasettings/index/view/id/'.$_product->getId());?>');" title="<?php echo $this->__('Quick View') ?>" class="button detail-bnt"><span><?php echo $this->__('Quick View') ?></span></a>
                             </div> <!--product-detail-bnt-->
                          </div> <!--box-inner-->
                       </div> <!--item-box-hover-->
                    <?php } ?> 
                     </div> <!--item-img-info-->
                   </div> <!--item-img-->

                  <div class="item-info">
                    <div class="info-inner">
                       <div class="item-title">
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                           <?php $prod_name = $this->htmlEscape($_product->getName()) ; 
                           if(strlen($prod_name) > 20) {echo substr($prod_name,0,20)."...";}else {echo $prod_name;}?>
                        </a>
                       </div> <!--item-title-->
                       <div class="item-content">
                    <?php
                        $summaryData = Mage::getModel('review/review_summary')
                                ->setStoreId($storeId)
                                ->load($_product->getId());
                        if($summaryData->getRatingSummary()){ ?>
                            <div class="ratings">
                                <div class="rating-box">
                                        <div class="rating" style="width: <?php echo $summaryData->getRatingSummary().'%'; ?>"></div>
                                </div> <!--rating-box-->
                            </div> <!--ratings-->
                    <?php } else { ?>  
                            <div class="no-rating-box-blank"><div class="no-rating-box"></div></div>
                    <?php } ?>
                          <div class="item-price">
                             <?php echo $this->getPriceHtml($_product, true) ?>
                          </div> <!--item-price-->
                       </div> <!--item-content-->
                    </div> <!--info-inner-->

                     <div class="actions">
                       <span class="add-to-links">
                          <?php if ($this->helper('wishlist')->isAllow()) : ?>
                             <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist" title="<?php echo $this->__('Add to wishlist');?>"></a>
                          <?php endif; ?>
                          <?php if($_product->isSaleable()): ?>
                             <button type="button"  title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
                          <?php else: ?>
                             <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                          <?php endif; ?>
                          <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                             <a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to compare');?>"></a>
                          <?php endif; ?> 
                       </span> <!--add-to-links-->
                     </div> <!--actions-->

                  </div> <!--item-info-->
                 </div> <!--item-inner-->                
                </li>

            <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
            
            <?php endif ?>
            
                <?php endforeach ?>
          </ul>
       </div> <!--jcarousel-clip jcarousel-clip-horizontal-->
     </div> <!--jcarousel-container jcarousel-container-horizontal-->
  </div> <!-- jcarousel-skin-tango5 -->
</div> <!--best-sales-slider-->


      <?php endif ?>  <!--Endif !$collection->count() -->
<?php } ?> <!-- chk attribute_code -->

<script type="text/javascript">
jQuery(document).ready(function($) {

        function mycarousel_initCallback(carousel) {
            $('#products_slider_next2').bind('click', function() {
                carousel.next();
                return false;
            });
            $('#products_slider_prev2').bind('click', function() {
                carousel.prev();
                return false;
            });
        };

    $('#products_slider2').jcarousel({
            scroll: 1,
        initCallback: mycarousel_initCallback,
            buttonNextHTML: null,
            buttonPrevHTML: null
    });
});
</script>

<div id="mgkquickview">
<div id="magikloading" style="display:none;text-align:center;margin-top:400px;"><img src="<?php echo $this->getSkinUrl('images/mgkloading.gif');?>" alt="loading">
</div></div>
<script type="text/javascript">
function callQuickView(qurl) { 
    jQuery('#mgkquickview').show();
    jQuery('#magikloading').show();
    jQuery.get(qurl, function(data) {
      jQuery.fancybox(data);
      jQuery('#magikloading').hide();
jQuery('#mgkquickview').hide();
    });
 }
 
</script>

</div>
