<div id="disabled-content" class="disabled-content">
	<h2>
		<span class = "disabled-content-header"> <?php echo $this->__('Oops, this feature is not available in your Lite Inventory edition') ?> </span>
	</h2>
	<div class="disabled-content-main">
		<div class="main-upper">
			<img>

			</img>
			<label class="main-upper-notice">
				<?php echo $this->__("Plus you'd love to have control of more than 11 functions to master your inventory system") ?>
			</label>
		</div>
		<div class="content-main-list-features">
			<div class="lite-features">
				<div class="main-list-header">
					<span>
						<b><?php echo $this->__("LITE ") ?></b>
						<span><?php echo $this->__(" - Your current plan") ?></span>
					<span>
					
				</div>
				<ul class="lite-features-list" >
					<li><?php echo $this->__("Stock Management") ?></li>
					<li><?php echo $this->__("Stock Adjustment") ?></li>
					<li><?php echo $this->__("Stock Receiving") ?></li>
				</ul>
			</div>
			<div class="plantinum-features">
				<div class="main-list-header">
					<span>
						<b><?php echo $this->__("PREMIUM ") ?></b>
						<span><?php echo $this->__(" - Everything you get with Lite Inventory, plus:") ?></span>
					<span>
				</div>
				<ul class="plantinum-features-list">
					<li><?php echo $this->__("Stock Purchase") ?></li>
					<li><?php echo $this->__("Supplier Portfolios") ?></li>
					<li><?php echo $this->__("Low Stock Notifications") ?></li>
					<li><?php echo $this->__("Shipment Status") ?></li>
					<li><?php echo $this->__("Inventory Dashboard") ?></li>
					<li><?php echo $this->__("Multiple Warehouses") ?></li>
					<li><?php echo $this->__("Barcode Management") ?></li>
					<li><?php echo $this->__("Physical Stocktaking") ?></li>
					<li><?php echo $this->__("Supply Need Forecast") ?></li>
					<li><?php echo $this->__("Inventory Reports") ?></li>
					<li><?php echo $this->__("Drop Shipping") ?></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="disabled-content-button">
		<button>
			<span>
				<span>
					<?php echo strtoupper($this->__("Unlock 11+ Advanced Features")) ?>
				</span>
			</span>
		</button>
	</div>
</div>

<style type="text/css">
	.disabled-content{
		width:100%;
	}
	.disabled-content .disabled-content-main{
		width:100%;
	}
	.disabled-content .content-main-list-features{
		width:100%;
	}
	.disabled-content h2 .disabled-content-header {
		color: #21A0DB;
		text-align:center;
	}
	.main-upper-notice{
		font-size:1.1em;
		font-weight: bolder;
	}
	.main-list-header{
		padding:10px;
		width:100%;
		float:left;
		color: #fff;
		background-color:#21A0DB;
		font-size:1.25em;
	}
	.main-list-header span{
		color: #fff;
	}
	.main-list-header span span{
		font-style:italic;
	}
	.content-main-list-features .lite-features{
		float:left;
		width:40%;
	}
	.content-main-list-features .lite-features-list{
		padding:10px;
		float:left;
		width:100%;
	}
	.content-main-list-features .plantinum-features{
		float:left;
		width:58%;
	}
	.content-main-list-features .plantinum-features-list{
		padding:10px;
		float:left;
		width:100%;
	}
</style>




