<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html>
<html lang="<?php echo $this->getLang() ?>">
<head>
<?php echo $this->getChildHtml('head') ?>
</head>

<body class="<?php echo Mage::getStoreConfig('innovasettings/innovasettings_appearance/width'); echo $this->getBodyClass()?' '.$this->getBodyClass().'':'' ?>" itemscope itemtype="http://schema.org/WebPage">
<!-- BEGIN PAGE -->
    <?php echo $this->getChildHtml('after_body_start') ?>
    <?php echo $this->getChildHtml('global_notices') ?>
    
    <?php echo $this->getChildHtml('header') ?> 
<!-- HOME PAGE SLIDER -->
       <?php echo $this->getLayout()->createBlock('catalog/product')->setTemplate('catalog/product/slider.phtml')->toHtml() ; ?>
<!-- welcome block -->
    <section class="section-welcome">
        <div class="main-col">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('welcome')->toHtml() ?>
        </div>
    </section>
<!-- Home Featured Block -->
       <?php 
        //if(Mage::getSingleton('Mage_Reports_Block_Product_Viewed')->getItemsCollection()->count()>0){
            echo $this->getLayout()->createBlock('cms/block')->setBlockId('innova_home_featured_recently_block')->toHtml();
        //}
        //else{
        //    echo $this->getLayout()->createBlock('cms/block')->setBlockId('innova_home_featured_block')->toHtml();
        //} 
        ?>
<!-- BEGIN MAIN CONTAINER COL1 LAYOUT -->     
            <div class="main-col">
                <article>
                    <?php echo $this->getChildHtml('breadcrumbs') ?>
                    <?php echo $this->getChildHtml('global_messages') ?>
                    <?php echo $this->getChildHtml('content') ?>
                </article>
            </div> <!--main-col-->
            
            <section>
                <div class="main-col">
                <?php echo $this->getLayout()->createBlock('catalog/product_list')->setTemplate('catalog/product/bestseller.phtml')->toHtml() ; ?>
                </div>
            </section>
            <!-- Home Featured Product Section -->
            <section>
                <?php echo $this->getLayout()->createBlock('catalog/product_list')->setTemplate('catalog/product/featured.phtml')->toHtml() ; ?>
            </section>
            <!-- Home offer banner block -->
            <?php 
            if(Mage::getSingleton('cms/page')->getIdentifier() == 'home' && Mage::app()->getFrontController()->getRequest()->getRouteName() == 'cms'){
                echo $this->getLayout()->createBlock('cms/block')->setBlockId('innova_home_offer_banner_news_block')->toHtml();
            }
            else{
                echo $this->getLayout()->createBlock('cms/block')->setBlockId('innova_home_offer_banner_block')->toHtml();
            }
             ?>
            <!-- Home Lastest Blog Block -->
            <!-- <section>
                <?php // echo $this->getLayout()->createBlock('cms/block')->setBlockId('innova_home_latest_blog_block')->toHtml() ?>
            </section> -->
            <!-- Home Testimonial Block commented out-->
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('innova_home_testimonial_block')->toHtml() ?>
            <!-- Logo Brand Section -->
            <section><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('innova_logo_brand_block')->toHtml() ?></section>
            <section><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('innova_footer_freeshipping_banner_block')->toHtml() ?></section>
        <?php echo $this->getChildHtml('footer') ?>
        <?php echo $this->getChildHtml('before_body_end') ?>
        <?php echo $this->getAbsoluteFooter() ?>

<!-- Home page newsletter -->
<?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/subscribe_footer.phtml')->toHtml() ; ?>

</body>
</html>

