
<?php if (Mage::getStoreConfig('innovasettings/innovasettings_products/upsell_product')): ?>

<?php if(count($this->getItemCollection()->getItems())): ?>

<?php $_helper = $this->helper('catalog/output'); ?>

<!-- BEGIN BOX COLLATERAL BOX UP SELL -->
<div class="upsell-block">
  <div class="block-title">
     <h2><span><?php echo $this->__('Produsul Următor') ?></span></h2>
  </div> <!--page-title-->
<a id="products_slider_prev1" class="jcarousel-prev-horizontal1" href="#"></a>
<a id="products_slider_next1" class="jcarousel-next-horizontal1" href="#"></a>
<div class="block-content">
  <div id="upsell-product-table">      
    <?php // $this->setColumnCount(5); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
    <?php $this->resetItemsIterator() ?>

<div class="jcarousel-skin-tango5">
    <div class="jcarousel-container jcarousel-container-horizontal" style="position: relative; display: block;">
      <div class="jcarousel-clip jcarousel-clip-horizontal" style="overflow: hidden; position: relative;">
        <ul class="products-grid jcarousel-list jcarousel-list-horizontal" id="products_slider" style="overflow: hidden; position: relative; top: 0px; margin: 0px; padding: 0px; left: -1176px; width: 2452px;">
        
    <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
            <?php if($_link=$this->getIterableItem()): ?>
            <li class="item jcarousel-item jcarousel-item-horizontal jcarousel-item-1 jcarousel-item-1-horizontal">
               <div class="item-inner">
                 <div class="item-img">
                    <div class="item-img-info">
                       <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image">
                         <img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(245,245) ?>" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" />
                       </a>
                       <?php echo $this->helper('innovasettings')->getLabel($_link);  ?>

                   <?php if(Mage::app()->getStore()->getConfig('innovasettings/innovasettings_quickview/enable')==1){?>
                    <div class="item-box-hover">
                       <div class="box-inner">
                          <div class="product-detail-bnt">
                              <a data-fancybox-type="ajax" onclick="callQuickView('<?php echo Mage::getUrl('innovasettings/index/view/id/'.$_link->getId());?>');" title="<?php echo $this->__('Quick View') ?>" class="button detail-bnt"><span><?php echo $this->__('Quick View') ?></span></a>                    
                          </div> <!--product-detail-bnt-->
                       </div> <!--box-inner-->
                    </div> <!--item-box-hover-->
                   <?php } ?>

                    </div> <!--item-img-info-->
                 </div> <!--item-img-->
                 <div class="item-info">
                   <div class="info-inner">
                    <div class="item-title">
                        <a class="product-name" href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->stripTags($_link->getName(), null, true) ?>">
                          <?php $prod_name = $this->htmlEscape($_link->getName()) ; 
                           if(strlen($prod_name) > 20) {echo substr($prod_name,0,20)."...";}else {echo $prod_name;}?>
                        </a>
                    </div> <!--item-title-->
                    <div class="item-content">
                    <?php
                        $summaryData = Mage::getModel('review/review_summary')
                                ->setStoreId($storeId)
                                ->load($_link->getId());
                        if($summaryData->getRatingSummary()){ ?>
                            <div class="ratings">
                                <div class="rating-box">
                                        <div class="rating" style="width: <?php echo $summaryData->getRatingSummary().'%'; ?>"></div>
                                </div> <!--rating-box-->
                            </div> <!--ratings-->
                    <?php } else { ?>  
                            <div class="no-rating-box-blank"><div class="no-rating-box"></div></div>
                    <?php } ?>
                       <div class="item-price">
                          <?php echo $this->getPriceHtml($_link, true, '-upsell') ?>
                       </div> <!--item-price-->
                    </div> <!--item-content-->
                   </div> <!--info-inner-->

                  <div class="actions">
                     <span class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                          <a href="<?php echo $this->helper('wishlist')->getAddUrl($_link) ?>" class="link-wishlist" title="<?php echo $this->__('Add to wishlist');?>"></a>
                        <?php endif; ?>
                        <?php if($_link->isSaleable()): ?>
                          <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_link) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
                        <?php else: ?>
                          <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_link)): ?>
                          <a href="<?php echo $_compareUrl ?>" class="link-compare" title="<?php echo $this->__('Add to compare');?>"></a>
                        <?php endif; ?>
                     </span> <!--add-to-links-->
                  </div> <!--actions-->

                 </div> <!--item-info-->
              </div> <!--item-inner-->                                                                    
            </li>
            <?php else: ?>
            <?php /* <li class="empty">&nbsp;</li> */ ?>
            <?php endif; ?>
        <?php endfor; ?>
    <?php endfor; ?>
          </ul>
       </div> <!--jcarousel-clip jcarousel-clip-horizontal-->
     </div> <!--jcarousel-container jcarousel-container-horizontal-->
</div> <!--jcarousel-skin-tango5-->

  </div>  <!--upsell-product-table-->
</div> <!--block-content--> 
</div> <!--upsell-block-->

<script type="text/javascript">
jQuery(document).ready(function($) {

        function mycarousel_initCallback(carousel) {
            $('#products_slider_next1').bind('click', function() {
                carousel.next();
                return false;
            });
            $('#products_slider_prev1').bind('click', function() {
                carousel.prev();
                return false;
            });
        };

    $('#products_slider').jcarousel({
            scroll: 1,
        initCallback: mycarousel_initCallback,
            buttonNextHTML: null,
            buttonPrevHTML: null,
itemFallbackDimension: 300
    });
});
</script>

<?php endif ?>

<?php endif; ?> 

<script type="text/javascript">decorateTable('upsell-product-table')</script>

<div id="mgkquickview">
<div id="magikloading" style="display:none;text-align:center;margin-top:400px;"><img src="<?php echo $this->getSkinUrl('images/mgkloading.gif');?>" alt="loading" width="35" height="35" />
</div></div>
<script type="text/javascript">
function callQuickView(qurl) { 
    jQuery('#mgkquickview').show();
    jQuery('#magikloading').show();
    jQuery.get(qurl, function(data) {
      jQuery.fancybox(data);
      jQuery('#magikloading').hide();
jQuery('#mgkquickview').hide();
    });
 }
 </script>

