<?php foreach ($this->getItems() as $item):?>
<li>
    <a href="<?php echo $item->getUrl()?>">
    <?php if ($item->getImgBig()) : ?>
        <?php
        $dimensions = getimagesize($item->getImgBig());
        /*
        echo '<!-- ';
        print_r($dimensions);
        echo ' -->';
        */
        ?>
        <img class="amshopby-featured" title="<?php echo $this->htmlEscape($item->getTitle())?>" alt="<?php echo $this->htmlEscape($item->getTitle())?>" src="<?php echo $item->getImgBig() ?>" <?php echo $dimensions[3]; ?> />
    <?php else: ?>
        <?php echo $this->htmlEscape($item->getTitle())?>
    <?php endif ?>
    </a>
</li>
<?php endforeach ?>
