<?php


    $warehouse_id = Mage::getModel('inventoryplus/warehouse')->getCollection()->getFirstItem()->getId();

$warehouse = Mage::getModel('inventoryplus/warehouse')->load($warehouse_id);
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Stock Receiving Information') ?></h4>
    </div>
    <div id="adjuststock_form" class="fieldset ">
        
            <label for="warehouse"><strong><?php echo $this->__('Reason(s) for stock received')?><?php if ($this->getRequest()->getParam('id')) echo ':' ?><?php echo ' '?></strong>
                <span class="required">*</span>
            </label>
            <br />
          
                <textarea id="reason" name="reason" title="Reason(s) for stock received" style="width:350px; height:50px;" rows="2" cols="15" class="textarea required-entry"><?php if ($this->getRequest()->getParam('id') && Mage::getModel('inventoryplus/adjuststock')->load($id)->getStatus()==0){ echo nl2br($adjustStock->getReason()); }?></textarea>
        
        </div>
        <div class="clear"></div>
    </div>
</div>

    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Import Products Received') ?></h4>
        </div>
        <div id="adjuststock_form" class="fieldset ">
            <?php //import product form ?>
            <div style="float:left;">
                <div>
                    <label for="fileToUpload">
                        <?php echo $this->__('Please choose a CSV file to import') ?>
                    </label><br />
                    <input type="file" name="fileToUpload[]" id="fileToUpload" onchange="fileSelected();" enctype="multipart/form-data"/>
                    <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" id="form_key"/>
                    <button style="" onclick="uploadFile()" class="scalable task" type="button" id="Upload"><span><?php echo $this->__('Import') ?></span></button>
                </div>
                <div class="clear"></div>
                <div id="fileName">
                </div>
                <div id="fileSize">
                </div>
                <div id="fileType">
                </div>
                <div id="progressNumber">
                </div>
            </div>
            <div id="messages" style="float: left;padding-left: 20px;width:60%;">
                <ul class="messages">
                    <li class="notice-msg">
                        <ul>
                            <li>
                                <?php echo $this->__('"If you want to import loads of receiving products, the structure of CSV file is as follows:') ?><br />                                                                       
                                <?php $example = "SKU: SKU of product received<br />" ?>                                   
                                <?php $example .= "QTY: Quantity of product received<br />" ?>                                                                  
                                <?php echo "<h3><b>SKU,QTY</b></h3>" ?>
                                <div style="padding-left: 20px;" ?>
                                    <?php echo $example ?>
                                </div>
                            </li>
                            <li>
                                <div style="float:left;">
                                    <b><?php echo $this->__('Example file') ?> (<a href="<?php echo Mage::getBaseUrl('media') . 'inventoryplus/csv/import_product_to_receive_stock.csv'; ?>"><?php echo $this->__('Download') ?></a>)</b>
                                </div>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="clear"></div>
        </div>
    </div>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend">
           
                <?php echo $this->__('Choose Products Received') ?>
           
        </h4>
    </div>
</div>