<?php
/** @var $this Webkul_NewsTicker_Block_Newsticker */

if (Mage::getStoreConfig('mm_extra/am_vazut_si_nea_placut/produs')!='') : 
    $_product = Mage::getModel('catalog/product')->loadByAttribute('sku', 
            Mage::getStoreConfig('mm_extra/am_vazut_si_nea_placut/produs'));
    $_blockProduct = $this->getLayout()->createBlock('catalog/product');
	$cart = new Mage_Catalog_Block_Product_List();
?>

<div class="item">
    <div class="product-image">
    <a href="<?php echo $_product->getProductUrl() ?>" 
       title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" 
       class="">
        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(230, 230); ?>" 
           width="230"
           height="230" 
           alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />             
    </a>
    </div> <!--product-image-->

    <div class="product-shop">
        <h2 class="product-name">
            <a class="product-name" 
               href="<?php echo $_product->getProductUrl() ?>" 
               title="<?php echo $this->stripTags($_product->getName(), null, true) ?>">
                <?php $prod_name = $this->htmlEscape($_product->getName()) ; 
                  echo $prod_name;
                ?>
            </a>
        </h2>
        <div class="desc std">
           <div class="item-price">
              <?php echo $_blockProduct->getPriceHtml($_product, true); ?>
           </div> <!--item-price-->
        </div>  
      
        <div class="actions">
            <button type="button"  title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $cart->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
        </div>
    </div>  
</div> 
<?php endif; 

